name: build API documentation

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.6.6
          run_install: false      

      #TODO: implement caching (see: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
      # to prevent needing to run this all the time
      - name: Install dependencies
        run: pnpm install

      - name: Generate Typedocs
        run: pnpm run docs

      - uses: actions/upload-pages-artifact@v2
        name: Upload typedocs
        with:
          name: github-pages
          path: ./docs/
